# Generated by Django 4.1 on 2023-02-05 19:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0002_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="message",
            old_name="recipient",
            new_name="receiver",
        ),
    ]
