# Generated by Django 4.1 on 2023-02-06 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0005_alter_chatroom_room_id"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="message",
            options={"ordering": ("created",)},
        ),
        migrations.RenameField(
            model_name="chatroom",
            old_name="members",
            new_name="member",
        ),
        migrations.RenameField(
            model_name="message",
            old_name="timestamp",
            new_name="created",
        ),
        migrations.AddField(
            model_name="message",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="message",
            name="chatroom",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="messages",
                to="chat.chatroom",
            ),
        ),
    ]
